# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_segmento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Segmento')),
            ],
        ),
    ]
