# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_linkrss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
